@url = http://localhost:3322

### BASE
{{url}}

### EMPLOYEES
{{url}}/employees

### ADD EMPLOYEE
POST {{url}}/employee
content-type: application/json

{
	"employee": {
		"firstName": "hs",
		"lastName": "Schmidt"
	}
}